# Generated by Django 4.0.4 on 2022-04-16 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_interest_created_remove_interest_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='interest',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
