# Generated by Django 4.0.4 on 2022-04-16 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_interest_created_interest_modified_profile_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
